### PR TITLE
Apply patch from niceday mobile

### PR DESCRIPTION
**Pull request by cubicka**
Patch of changes related to local video.

### CODE REVIEW

**Comment by xaviraol** [comment]
These are basically the changes we applied in the app through the `patch-package`, right?
So in theory we could stop using the patched-module there and point to this forked-module, right?

Should we do it already @cubicka ? Or let's release to production with the patch for now and then we update calmly in develop for next version?

Tagging @jeffryadityatama as well.

**Comment by cubicka** [comment]
> So in theory we could stop using the patched-module there and point to this forked-module, right?

Yes!

> Should we do it already @cubicka ? Or let's release to production with the patch for now and then we update calmly in develop for next version?

If it's alright, let Twilio use patch, and EMDR will update it to this forked repo.
Twilio has gone a long way 😂

**Comment by xaviraol** [comment]
Okay sounds good! The Twilio ship has already sailed, so lets leave it like this.

**Review by xaviraol — APPROVED** [review]
Just tested it in the app, in iOS and Android and that works well.

**Pull request merged**
